### ISSUE TITLE
GlowAPI + PackListenerAPI Load Error

### ISSUE THREAD

**Issue by kiloRs** [InventivetalentDev/PacketListenerAPI#94] opened 2021-05-31 22:50 UTC
Starting the most recent versions on JAVA 11 using PAPER 1.16.5, I am unable to get GLOW API to load through PacketListenerAPI. I am unsure where the error is..

`[22:44:37] [Server thread/INFO]: [APIManager] API class 'org.inventivetalent.packetlistener.PacketListenerAPI' is not yet initialized. Creating new instance.
[22:44:37] [Server thread/ERROR]: Error occurred while enabling GlowAPI v1.4.15-SNAPSHOT (Is it up to date?)
java.lang.ClassCastException: org.inventivetalent.packetlistener.PacketListenerAPI incompatible with org.inventivetalent.apihelper.API
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:116) ~[?:?]
	at org.inventivetalent.glow.GlowAPI.init(GlowAPI.java:472) ~[?:?]
	at org.inventivetalent.apihelper.RegisteredAPI.init(RegisteredAPI.java:55) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:96) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:127) ~[?:?]
	at org.inventivetalent.glow.GlowPlugin.onEnable(GlowPlugin.java:22) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:311) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3136/000000009A461E10.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:836) [?:?]`

**Comment by qixils** [comment] 2021-06-21 18:36
Duplicate of https://github.com/InventivetalentDev/GlowAPI/issues/83 and fixed by https://github.com/InventivetalentDev/GlowAPI/releases/tag/1.4.16-SNAPSHOT

**Closed as completed** 2022-01-09 01:41 UTC
Labels: wontfix
